spring:
  #mvc:
  #  view:
  #    prefix: /WEB-INF/jsp/
  #    suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(DwUn1dByIGMkxfB4oYTgpVrT9ILF2Jim6BYPBh2RWeD6DkpUDf++g7WD+kH2bUfO+cLJ3s+bRDmbthtkvLdTLGTSHx0RUmM0XC25vrLsdjk=)
    username: ENC(ZOokZrKQZyYQgr+UXqvVOAMKZ9gDQyBI)
    password: ENC(ZOokZrKQZyYQgr+UXqvVOAMKZ9gDQyBI)
    hikari:
      connectionTimeout: 30000 # default: 30000(30sec)
      maximumPoolSize: 30 # default: 10
      maxLifeTime: 1800000 # default: 1800000(30minute)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        #hbm2ddl.auto: create-only # only create when no table
    show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  servlet:
    session:
      timeout: 30m
jasypt:
  encryptor:
    bean: jasyptStringEncryptor