spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shorturl
    username: shorturl
    password: shorturl
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        #hbm2ddl.auto: create-only # only create when no table
    show-sql: true